[phases.setup]
nixPkgs = ["glib", "gobject-introspection", "pango", "fontconfig", "harfbuzz", "cairo", "gdk-pixbuf", "libffi", "zlib", "shared-mime-info"]

[phases.install]
cmds = ["pip install -r requirements.txt"]
